### ISSUE TITLE
MultiByteToWideChar function in the Demo

### ISSUE THREAD

**Issue by goldenbutteredjam** [xlwings/xlwings-remote-fastapi#2]
I had to change lpMultiByteStr and lpWideCharStr in the WebResponse class from Long to a LongPtr type in the demo.xlsm for this to work on Windows.

```vb.net
#If Mac Then
#ElseIf VBA7 Then
Private Declare PtrSafe Function MultiByteToWideChar Lib "kernel32" ( _
   ByVal CodePage As Long, ByVal dwFlags As Long, _
   ByVal lpMultiByteStr As LongPtr, ByVal cchMultiByte As Long, _
   ByVal lpWideCharStr As LongPtr, ByVal cchWideChar As Long) As Long
#Else
```

**Comment by fzumstein** [comment]
Thanks for reporting! I see that this repo still uses xlwings 0.27.1 and the issue was fixed with 0.27.2. 
I will update it accordingly.
